/*!
 * froala_editor v1.2.8 (https://www.froala.com/wysiwyg-editor)
 * License https://www.froala.com/wysiwyg-editor/terms
 * Copyright 2014-2015 Froala Labs
 */

/**
 * English spoken in the US
 */

$.Editable.LANGS['en_us'] = {
  translation: {
    "Bold": "Bold",
    "Italic": "Italic",
    "Underline": "Underline",
    "Strikethrough": "Strikethrough",
    "Font Size": "Font Size",
    "Color": "Color",
    "Background": "Background",
    "Text": "Text",
    "Format Block": "Format Block",
    "Normal": "Normal",
    "Paragraph": "Paragraph",
    "Code": "Code",
    "Quote": "Quote",
    "Heading 1": "Heading 1",
    "Heading 2": "Heading 2",
    "Heading 3": "Heading 3",
    "Heading 4": "Heading 4",
    "Heading 5": "Heading 5",
    "Heading 6": "Heading 6",
    "Block Style": "Block Style",
    "Alignment": "Alignment",
    "Align Left": "Align Left",
    "Align Center": "Align Center",
    "Align Right": "Align Right",
    "Justify": "Justify",
    "Numbered List": "Numbered List",
    "Bulleted List": "Bulleted List",
    "Indent Less": "Indent Less",
    "Indent More": "Indent More",
    "Select All": "Select All",
    "Insert Link": "Insert Link",
    "Insert Image": "Insert Image",
    "Insert Video": "Insert Video",
    "Undo": "Undo",
    "Redo": "Redo",
    "Show HTML": "Show HTML",
    "Float Left": "Float Left",
    "Float None": "Float None",
    "Float Right": "Float Right",
    "Replace Image": "Replace Image",
    "Remove Image": "Remove Image",
    "Title": "Title",
    "Drop image": "Drop image",
    "or click": "or click",
    "or": "or",
    "Enter URL": "Enter URL",
    "Please wait!": "Please wait!",
    "Are you sure? Image will be deleted.": "Are you sure? Image will be deleted.",
    "UNLINK": "UNLINK",
    "Open in new tab": "Open in new tab",
    "Type something": "Type something",
    "Cancel": "Cancel",
    "OK": "OK",
    "Manage images": "Manage images",
    "Delete": "Delete",
    "Font Family": "Font family",
    "Insert Horizontal Line": "Insert Horizontal Line",
    "Table": "Table",
    "Insert table": "Insert table",
    "Cell": "Cell",
    "Row": "Row",
    "Column": "Column",
    "Delete table": "Delete table",
    "Insert cell before": "Insert cell before",
    "Insert cell after": "Insert cell after",
    "Delete cell": "Delete cell",
    "Merge cells": "Merge cells",
    "Horizontal split": "Horizontal split",
    "Vertical split": "Vertical split",
    "Insert row above": "Insert row above",
    "Insert row below": "Insert row below",
    "Delete row": "Delete row",
    "Insert column before": "Insert column before",
    "Insert column after": "Insert column after",
    "Delete column": "Delete column",
    "Uploading image": "Uploading image",
    "Upload File": "Upload File",
    "Drop File": "Drop File",
    "Clear formatting": "Clear formatting"
  },
  direction: "ltr"
};
