/*!
 * froala_editor v1.2.7 (https://www.froala.com/wysiwyg-editor)
 * License https://www.froala.com/wysiwyg-editor/terms
 * Copyright 2014-2015 Froala Labs
 */

$.Editable.LANGS['et'] = {
  translation: {
    "Bold": "Rasvane",
    "Italic": "Kursiiv",
    "Underline": "Allajoonitud",
    "Strikethrough": "L\u00e4bikriipsutatud",
    "Font Size": "Fondi suurus",
    "Color": "V\u00e4rv",
    "Background": "Taust",
    "Text": "Tekst",
    "Format Block": "Formaadi plokk",
    "Normal": "Normaalne",
    "Paragraph": "Paragrahv",
    "Code": "Kood",
    "Quote": "Tsitaat",
    "Heading 1": "P\u00e4is 1",
    "Heading 2": "P\u00e4is 2",
    "Heading 3": "P\u00e4is 3",
    "Heading 4": "P\u00e4is 4",
    "Heading 5": "P\u00e4is 5",
    "Heading 6": "P\u00e4is 6",
    "Block Style": "Ploki stiil",
    "Alignment": "Joondamine",
    "Align Left": "Joonda vasakule",
    "Align Center": "Joonda keskele",
    "Align Right": "Joonda paremale",
    "Justify": "R\u00f6\u00f6pjoondus",
    "Numbered List": "Nummerdatud nimekiri",
    "Bulleted List": "Mummudega nimekiri",
    "Indent Less": "V\u00e4henda taanet",
    "Indent More": "Lisa taanet",
    "Select All": "Vali k\u00f5ik",
    "Insert Link": "Lisa link",
    "Insert Image": "Lisa pilt",
    "Insert Video": "Lisa video",
    "Undo": "V\u00f5ta tagasi",
    "Redo": "Tee uuesti",
    "Show HTML": "N\u00e4ita HTML-i",
    "Float Left": "H\u00f5ljuta vasakule",
    "Float None": "\u00e4ra h\u00f5ljuta",
    "Float Right": "H\u00f5ljuta paremale",
    "Replace Image": "Asenda pilt",
    "Remove Image": "Eemalda pilt",
    "Title": "Pealkiri",
    "Drop image": "Aseta pilt",
    "or click": "v\u00f5i kliki",
    "or": "v\u00f5i",
    "Enter URL": "Sisesta URL",
    "Please wait!": "Palun oota!",
    "Are you sure? Image will be deleted.": "Oled sa kindel? Pilt kustutatakse.",
    "UNLINK": "EEMALDA LINK",
    "Open in new tab": "Ava uues sakis",
    "Type something": "Kirjuta midagi",
    "Cancel": "T\u00fchista",
    "OK": "OK",
    "Manage images": "Halda pilte",
    "Delete": "Kustuta",
    "Font Family": "Fondi perekond",
    "Insert Horizontal Line": "Sisesta horisontaalne joon",
    "Table": "Tabel",
    "Insert table": "Sisesta tabel",
    "Cell": "Lahter",
    "Row": "Rida",
    "Column": "Veerg",
    "Delete table": "Kustuta tabel",
    "Insert cell before": "Sisesta lahter ette",
    "Insert cell after": "Sisesta lahter j\u00e4rele",
    "Delete cell": "Kusuta lahter",
    "Merge cells": "\u00fchenda lahtrid",
    "Horizontal split": "Poolita horisontaalselt",
    "Vertical split": "Poolita vertikaalselt",
    "Insert row above": "Sisesta rida \u00fcles",
    "Insert row below": "Sisesta rida alla",
    "Delete row": "Kustuta rida",
    "Insert column before": "Sisesta veerg ette",
    "Insert column after": "Sisesta veerg j\u00e4rele",
    "Delete column": "Kustuta veerg",
    "Uploading image": "Pildi \u00fcleslaadimine",
    "Upload File": "Lae fail \u00fcles",
    "Drop File": "Aseta fail",
    "Clear formatting": "Eemalda formaatimine"
  },
  direction: "ltr"
};