/*!
 * froala_editor v1.2.3 (http://editor.froala.com)
 * Copyright 2014-2014 Froala
 */

/**
 * Russian
 */

$.Editable.LANGS['ru'] = {
  translation: {
    "Bold": "Жирный",
    "Italic": "Курсив",
    "Underline": "Подчеркнутый",
    "Strikethrough": "Зачеркнутый",
    "Font Size": "Размер шрифта",
    "Color": "Цвет",
    "Background Color": "Цвети фона",
    "Text Color": "Цвет текста",
    "Format Block": "Формат",
    "Normal": "Нормальный",
    "Paragraph": "Параграф",
    "Code": "Код",
    "Quote": "Цитата",
    "Heading 1": "Заголовок 1",
    "Heading 2": "Заголовок 2",
    "Heading 3": "Заголовок 3",
    "Heading 4": "Заголовок 4",
    "Heading 5": "Заголовок 5",
    "Heading 6": "Заголовок 6",
    "Block Style": "Стиль блока",
    "Alignment": "Выравнивание",
    "Align Left": "По левому краю",
    "Align Center": "По центру",
    "Align Right": "По правому краю",
    "Justify": "По ширине",
    "Numbered List": "Нумерованный список",
    "Bulleted List": "Маркированный список",
    "Indent Less": "Уменьшить отступ",
    "Indent More": "Увеличить отступ",
    "Select All": "Выбрать все",
    "Insert Link": "Вставить ссылку",
    "Insert Image": "Вставить изображение",
    "Insert Video": "Вставить видео",
    "Undo": "Вернуть",
    "Redo": "Повторить",
    "Show HTML": "Показать HTML",
    "Float Left": "Обтекание справа",
    "Float None": "Нет обтекания",
    "Float Right": "Обтекание слева",
    "Replace Image": "Заменить изображение",
    "Remove Image": "Удалить изображение",
    "Title": "Название",
    "Insert image": "Вставка изображения",
    "Drop image": "Переместите сюда файл",
    "or click": "или нажмите",
    "or": "или",
    "Enter URL": "Введите URL",
    "Please wait!": "Пожалуйста подождите!",
    "Are you sure? Image will be deleted.": "Вы уверены? Изображение будет удалено.",
    "UNLINK": "Удалить ссылку",
    "Open in new tab": "Открыть в новой вкладк",
    "Type something": "Напишите что-нибудь",
    "Cancel": "Отменить",
    "OK": "OK",
    "Manage images": "Управление изображениями",
    "Delete": "Удалить",
    "Font Family": "Шрифт",
    "Insert Horizontal Line": "Вставить горизонтальную линию",
    "Table": "Таблица",
    "Insert table": "Вставить таблицу",
    "Cell": "Ячейка",
    "Row": "Строка",
    "Column": "Столбец",
    "Delete table": "Удалить таблицу",
    "Insert cell before": "Вставить ячейку до",
    "Insert cell after": "Вставить ячейку после",
    "Delete cell": "Удалить ячейку",
    "Merge cells": "Объеденить ячейки",
    "Horizontal split": "Разделить горизонтально",
    "Vertical split": "Разделить вертикально",
    "Insert row above": "Вставить пустую строку сверху",
    "Insert row below": "Вставить пустую строку снизу",
    "Delete row": "Удалить строку",
    "Insert column before": "Добавить столбец слева",
    "Insert column after": "Добавить столбец справа",
    "Delete column": "Удалить столбец"
  },
  direction: "ltr"
};
